package JTable;

import static BibTeX.fayılridır.cleaner;
import static BibTeX.fayılridır.parseleft;
import static BibTeX.fayılridır.parseright;
import static BibTeX.fayılridır.removeDuplicates;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.NoSuchElementException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LayThese
 */
public class JTable_Denemesi extends javax.swing.JFrame {

    /**
     * Creates new form JTable_Denemesi
     */
    public JTable_Denemesi() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("Open");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Delete");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {                                    
                        String userDir = System.getProperty("user.home");
                        JFileChooser fc = new JFileChooser(userDir +"/Desktop");
                        FileNameExtensionFilter filter = new FileNameExtensionFilter("BIB FILES", "bib", "BibTeX");
                        fc.setFileFilter(filter);
                        Component parent = null;
                        int returnVal = fc.showOpenDialog(parent);
                        Object[] tableRows = null;
                        if(returnVal == JFileChooser.APPROVE_OPTION)
                        {
                            try
                            {
                                File file = fc.getSelectedFile();
                                // Column Kısmı //
                                ArrayList <String> values2 = removeDuplicates((parseleft(file)));
                                Object[] Columns = values2.toArray();
                                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                                model.setColumnIdentifiers(Columns);
                                
                                // Row kısmı//
                                ArrayList <String> values = cleaner(parseright(file));
                                tableRows = values.toArray();
                                int a = 1;
                                
                                for(int i = 0; i< tableRows.length;i++) 
                                {
                                    if(tableRows[i].toString().contains("@") == true)
                                    {                                       
                                        model.setNumRows(a);
                                        a++;
                                        model.insertRow(i, tableRows);
                                    }
                                }
                                 
                                 JFrame f = new JFrame();  
                                 JOptionPane.showMessageDialog(f,+tableRows.length+ " kadar öge bulundu");
                                
                                //System.out.println(values);
                            } catch (HeadlessException | FileNotFoundException | NoSuchElementException ex) {
                                JOptionPane optionPane = new JOptionPane("Dosya okunurken bir hata oluştu.", JOptionPane.ERROR_MESSAGE);
                                JDialog dialog = optionPane.createDialog("Hata mesajı");
                                dialog.setVisible(true);
                            }catch(ArrayIndexOutOfBoundsException ex)
                            { 
                                JOptionPane optionPane = new JOptionPane("Tablo oluştururken bir hata oluştu", JOptionPane.ERROR_MESSAGE);
                                JDialog dialog = optionPane.createDialog("ArrayIndexOutOfBoundsException");
                                dialog.setVisible(true);
                            }
                        }             
    }                                   

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {                                    
       if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
    try {
        Desktop.getDesktop().browse(new URI("https://github.com/AtahanEkici/OBASEB"));
    } catch (URISyntaxException | IOException ex) {
        Logger.getLogger(JTable_Denemesi.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    }                                   

    @SuppressWarnings("empty-statement")
    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {                                    
        ;
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTable_Denemesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTable_Denemesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTable_Denemesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTable_Denemesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JTable_Denemesi().setVisible(true);
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   

}
